# College Graduate Earnings
---
*by Ian McNabb*

The purpose of this notebook is to practice using Python, specifically the pandas, matplotlib, and numpy libraries, for parsing through data and creating visualizations. This is also used as an opportunity to refamiliarize myself with Jupyter Notebooks, creating new directories using bash, etc.

*data source credit:* [The Wall Street Journal](https://www.kaggle.com/wsj/college-salaries)

**Temporary workflow/notes below (no api)**

*struggling with requesting api for data, will come back to that*
- start with parsing datafile with csv library
    - How much do engineering degrees start off making in their career? Make a bar chart comparing them
        - cannot convert string to float? Trying to convert row[1] (median salary) to float
            - SOLVED: just needed a nights rest to realize it was the '$' and the ','
        - created module 'format_salary' that returns an integer from read salary strings
        - Having problems rendering pygal graph within jupyter notebook
            - pygal seems to be out of date and not very compatible with ipython. Switched to matplotlib to make it easy
    - What is the average median starting salary for every school type (engineering, party, liberal arts, state)?
        - I realize this process would be quicker and easier in excel, but the point is to practice and learn python even if it's inefficient and using brute force at first
        - figuring out how to create a dictionary containing a list of values for each key, then traversing through it
        - using arrays from the numpy library may be a more efficient way to store and manipulate data in this situation
        - what does *zip function even do? Seems like an easy solution plotting dictionaries
            - Breaking down the code... items() method returns the dictionary as a list of tuples. "A view object that displays a list of a given dictionary's (key, value) tuple pair."
            - zip() function takes iterables (lists, tuples, dict), aggregates them in a tuple, and returns it.
            - might have something to do with positional arguments (*args). I understand that in the context of a creating a function but I still don't get what exactly it's doing here
- spent a substantial amount of time learning about pandas (dataframes, series, sorting, filtering, grouping, etc.), now it's finally time to apply that knowledge.
    - Why is the data type object and not string for each column??

In [ ]:
import csv 
import matplotlib.pyplot as plt
from statistics import mean

# takes string in $xx,xxx.xx format and converts to integer
from format_salary import format_salary

**1. What is the median starting salary for all engineering majors?**

In [ ]:
filepath = "college-salaries/degrees-that-pay-back.csv"

with open(filepath, 'r') as f_obj:
    reader = csv.reader(f_obj)
    header_row = next(reader)
    
    salaries = []
    engineers = []
    for row in reader:
        name = row[0]
        salary = row[1]
        if 'Engineering' in name: 
            engineers.append(name)
            salaries.append(format_salary(salary))

In [ ]:
# create and format bar graph
plt.figure(figsize=(6.0,8.0))
plt.bar(engineers, salaries, width=0.5, bottom=0, log=True, color='b', alpha=0.5)
plt.xticks(rotation=20, horizontalalignment='right', fontsize='medium')
plt.xlabel('Majors', fontsize='xx-large', fontweight='heavy')
plt.ylabel('Starting Salary', fontsize='xx-large', fontweight='heavy')
plt.title("Engineering Majors Median Starting Salary", fontsize='xx-large', fontweight='heavy')
plt.show()

**2. What is the average median starting salary for every school type (engineering, party, liberal arts, state)?**

In [ ]:
filepath = "college-salaries/salaries-by-college-type.csv"

with open(filepath, 'r') as f_obj:
    reader = csv.reader(f_obj)
    header_row = next(reader)
    
    # initialize lists to store read salaries for each school type
    eng_salary, party_salary, lib_salary, state_salary, ivy_salary = ([] for i in range(5))
    school_type = ['Engineering', 'Party', 'Liberal Arts', 'State', 'Ivy League']
    
    # build lists
    for row in reader:
        if row[1] == school_type[0]:
            eng_salary.append(format_salary(row[2]))
        elif row[1] == school_type[1]:
            party_salary.append(format_salary(row[2]))
        elif row[1] == school_type[2]:
            lib_salary.append(format_salary(row[2]))
        elif row[1] == school_type[3]:
            state_salary.append(format_salary(row[2]))
        else:
            ivy_salary.append(format_salary(row[2]))
    
    # create dictionary with school type as keys and average median salaries as values
    my_dict = {}
    my_dict['Engineering'] = mean(eng_salary)
    my_dict['Party'] = mean(party_salary)
    my_dict['Liberal Arts'] = mean(lib_salary)
    my_dict['State'] = mean(state_salary)
    my_dict['Ivy League'] = mean(ivy_salary)
    
    print("Engineering school average median salary: " + str(round(mean(eng_salary), 2)))
    print("Party school average median salary: " + str(round(mean(party_salary), 2)))
    print("Liberal Arts school average median salary: " + str(round(mean(lib_salary), 2)))
    print("State school average median salary: " + str(round(mean(state_salary), 2)))
    print("Ivy League school average median salary: " + str(round(mean(ivy_salary), 2)))

In [ ]:
plt.figure(figsize=(6.0,8.0))
plt.bar(*zip(*my_dict.items()), width=0.5, color='g')
plt.xlabel('School Type', fontweight='heavy', fontsize='x-large')
plt.ylabel('Salary', fontweight='heavy', fontsize='xx-large')
plt.title('Average Median Starting Salary by School Type', fontsize='xx-large', fontweight='heavy')
plt.show()

## Pandas/NumPy Libraries
---

Now that I've learned how to use 'brute force' methods to explore data, it's time to learn how to use easier, more-efficient methods. In the realm of data science, pandas is unaminously the favorite library to use.

In [1]:
import numpy as np
import pandas as pd

from pandas_format_salary import format_pd

In [2]:
filepath = "college-salaries/salaries-by-region.csv"

df = pd.read_csv(filepath)

# pandas display options
# pd.reset_option('display.max_rows')
# pd.reset_option('display.max_columns')
pd.set_option('display.max_rows', None) # display all rows in dataset
pd.set_option('display.max_columns', None) # display all columns in dataset

df.head()

,School Name,Region,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
0,Stanford University,California,"$70,400.00","$129,000.00","$68,400.00","$93,100.00","$184,000.00","$257,000.00"
1,California Institute of Technology (CIT),California,"$75,500.00","$123,000.00",NaN,"$104,000.00","$161,000.00",NaN
2,Harvey Mudd College,California,"$71,800.00","$122,000.00",NaN,"$96,000.00","$180,000.00",NaN
3,"University of California, Berkeley",California,"$59,900.00","$112,000.00","$59,500.00","$81,000.00","$149,000.00","$201,000.00"
4,Occidental College,California,"$51,900.00","$105,000.00",NaN,"$54,800.00","$157,000.00",NaN

**Aggregate Statistics Grouped by Region:**

In [3]:
df_mod = df # create copy of df

In [4]:
df_mod.dtypes # why is data type object and not string?

School Name                          object
Region                               object
Starting Median Salary               object
Mid-Career Median Salary             object
Mid-Career 10th Percentile Salary    object
Mid-Career 25th Percentile Salary    object
Mid-Career 75th Percentile Salary    object
Mid-Career 90th Percentile Salary    object
dtype: object

In [5]:
columns = df.columns[2:] # create list of columns that have salary data
format_pd(df_mod, columns) # format salary columns into float type

,School Name,Region,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
0,Stanford University,California,70400.0,129000.0,68400.0,93100.0,184000.0,257000.0
1,California Institute of Technology (CIT),California,75500.0,123000.0,NaN,104000.0,161000.0,NaN
2,Harvey Mudd College,California,71800.0,122000.0,NaN,96000.0,180000.0,NaN
3,"University of California, Berkeley",California,59900.0,112000.0,59500.0,81000.0,149000.0,201000.0
4,Occidental College,California,51900.0,105000.0,NaN,54800.0,157000.0,NaN
5,Cal Poly San Luis Obispo,California,57200.0,101000.0,55000.0,74700.0,133000.0,178000.0
6,University of California at Los Angeles (UCLA),California,52600.0,101000.0,51300.0,72500.0,139000.0,193000.0
7,"University of California, San Diego (UCSD)",California,51100.0,101000.0,51700.0,75400.0,131000.0,177000.0
8,Pomona College,California,48600.0,101000.0,NaN,63300.0,161000.0,NaN
9,University of Southern California (USC),California,54800.0,99600.0,49700.0,73800.0,140000.0,201000.0
10,"University of California, Davis",California,52300.0,99600.0,52000.0,71600.0,135000.0,202000.0
11,"University of California, Irvine (UCI)",California,48300.0,96700.0,47800.0,66000.0,123000.0,172000.0
12,San Jose State University (SJSU),California,53500.0,95600.0,50700.0,70500.0,122000.0,156000.0
13,"University of California, Santa Barbara (UCSB)",California,50500.0,95000.0,51300.0,71200.0,129000.0,173000.0
14,"California State University (CSU), Chico",California,47400.0,88100.0,46800.0,62800.0,122000.0,154000.0
15,"California State University, Fullerton (CSUF)",California,45700.0,87000.0,45400.0,62500.0,119000.0,158000.0
16,San Francisco State University (SFSU),California,47300.0,86400.0,45100.0,62700.0,114000.0,150000.0
17,San Diego State University (SDSU),California,46200.0,85200.0,45500.0,61800.0,116000.0,158000.0
18,"California State University, Long Beach (CSULB)",California,45100.0,84700.0,47400.0,62500.0,113000.0,154000.0
19,"California State University, East Bay (CSUEB)",California,49200.0,84300.0,46000.0,62400.0,115000.0,155000.0
20,"University of California, Santa Cruz (UCSC)",California,44700.0,84100.0,46100.0,62000.0,121000.0,165000.0
21,"California State University, Sacramento (CSUS)",California,47800.0,82400.0,42900.0,59600.0,111000.0,154000.0
22,"University of California, Riverside (UCR)",California,46800.0,81300.0,37200.0,59900.0,109000.0,134000.0
23,"California State University, Northridge (CSUN)",California,45500.0,80400.0,44500.0,57800.0,108000.0,153000.0
24,"California State University, Dominguez Hills (...",California,42700.0,72100.0,30800.0,47000.0,92200.0,132000.0
25,"California State University (CSU), Stanislaus",California,38000.0,71400.0,NaN,50500.0,94100.0,NaN
26,Humboldt State University,California,42600.0,71300.0,36000.0,56300.0,94400.0,117000.0
27,Thomas Aquinas College,California,41500.0,67500.0,NaN,44600.0,93100.0,NaN
28,Colorado School of Mines,Western,58100.0,106000.0,62200.0,87900.0,142000.0,201000.0
29,University of Colorado - Boulder (UCB),Western,47100.0,97600.0,51600.0,69000.0,128000.0,187000.0
30,New Mexico Institute of Mining and Technology ...,Western,51000.0,93400.0,NaN,67400.0,123000.0,NaN
31,Brigham Young University (BYU),Western,49400.0,88600.0,50600.0,68500.0,119000.0,164000.0
32,University of Arizona,Western,47500.0,86100.0,44800.0,61700.0,117000.0,160000.0
33,University of Washington (UW),Western,48800.0,85300.0,47000.0,59800.0,115000.0,149000.0
34,Washington State University (WSU),Western,45300.0,84700.0,43600.0,59000.0,113000.0,162000.0
35,University of Colorado - Denver,Western,46100.0,84400.0,46400.0,58600.0,105000.0,144000.0
36,Arizona State University (ASU),Western,47400.0,84100.0,44600.0,60700.0,114000.0,163000.0
37,Oregon State University (OSU),Western,45100.0,83300.0,46900.0,64000.0,113000.0,146000.0
38,University of Utah,Western,45400.0,83200.0,43000.0,58400.0,116000.0,148000.0
39,"University of Nevada, Reno (UNR)",Western,46500.0,82900.0,41900.0,54600.0,113000.0,143000.0
40,Seattle University,Western,48300.0,82800.0,50600.0,62400.0,110000.0,150000.0
41,University of Idaho,Western,44900.0,82000.0,43000.0,56700.0,104000.0,142000.0
42,University of New Mexico (UNM),Western,41600.0,81600.0,41800.0,59100.0,105000.0,141000.0
43,University of Puget Sound,Western,46600.0,81500.0,48900.0,60100.0,104000.0,137000.0
44,Colorado College (CC),Western,38500.0,81400.0,NaN,43000.0,148000.0,NaN
45,Reed College,Western,40500.0,81100.0,NaN,67400.0,101000.0,NaN
46,Whitman College,Western,43500.0,80100.0,NaN,64800.0,111000.0,NaN
47,New Mexico State University,Western,44300.0,79500.0,37400.0,53800.0,102000.0,131000.0
48,Colorado State University (CSU),Western,44800.0,79000.0,43800.0,57100.0,112000.0,150000.0
49,University of Wyoming (UW),Western,44500.0,78700.0,41500.0,54000.0,105000.0,145000.0
50,Utah State University,Western,43800.0,78700.0,41600.0,55400.0,101000.0,132000.0
51,University of Oregon,Western,42200.0,78400.0,38100.0,56200.0,117000.0,186000.0
52,Montana State University - Bozeman,Western,46600.0,77500.0,40200.0,58100.0,111000.0,151000.0
53,Gonzaga University,Western,44900.0,76000.0,47000.0,57400.0,103000.0,138000.0
54,University of Hawaii,Western,43800.0,76000.0,40400.0,56300.0,104000.0,128000.0
55,Western Washington University,Western,42700.0,75400.0,41300.0,56700.0,99200.0,119000.0
56,Regis University,Western,48300.0,73800.0,41000.0,55500.0,94800.0,117000.0
57,Idaho State University,Western,44900.0,73400.0,35400.0,49600.0,101000.0,143000.0
58,"University of Alaska, Anchorage",Western,45900.0,72600.0,39800.0,56600.0,99300.0,137000.0
59,Lewis & Clark College,Western,38900.0,72600.0,38200.0,53400.0,104000.0,140000.0
60,University of Montana,Western,37300.0,71900.0,37000.0,51500.0,96400.0,138000.0
61,"University of Nevada, Las Vegas (UNLV)",Western,45200.0,71600.0,39000.0,52400.0,100000.0,128000.0
62,Portland State University (PSU),Western,42600.0,70900.0,40700.0,52300.0,94400.0,123000.0
63,Eastern Washington University,Western,38600.0,70900.0,36000.0,50500.0,93100.0,117000.0
64,Fort Lewis College,Western,42000.0,69800.0,NaN,55000.0,94000.0,NaN
65,Boise State University (BSU),Western,40800.0,69500.0,37400.0,48700.0,87500.0,110000.0
66,Utah Valley State College,Western,42400.0,67100.0,NaN,44100.0,84900.0,NaN
67,Evergreen State College,Western,39500.0,63900.0,38800.0,47200.0,91600.0,120000.0
68,Southern Utah University,Western,41900.0,56500.0,NaN,39700.0,78400.0,NaN
69,Montana State University - Billings,Western,37900.0,50600.0,NaN,31800.0,78500.0,NaN
70,University of Notre Dame,Midwestern,56300.0,116000.0,66400.0,85100.0,163000.0,235000.0
71,University Of Chicago,Midwestern,53400.0,113000.0,62200.0,83300.0,174000.0,255000.0
72,Carleton College,Midwestern,47500.0,103000.0,NaN,69400.0,141000.0,NaN
73,Illinois Institute of Technology (IIT),Midwestern,56000.0,97800.0,56100.0,77400.0,121000.0,165000.0
74,Case Western Reserve University,Midwestern,56200.0,96500.0,54900.0,76500.0,123000.0,168000.0
75,University of Illinois at Urbana-Champaign (UIUC),Midwestern,52900.0,96100.0,48200.0,68900.0,132000.0,177000.0
76,Northwestern University,Midwestern,52700.0,95900.0,51900.0,69100.0,144000.0,205000.0
77,University of Missouri - Rolla (UMR),Midwestern,57100.0,95800.0,67600.0,80400.0,122000.0,166000.0
78,South Dakota School of Mines & Technology,Midwestern,55800.0,93400.0,71500.0,81900.0,122000.0,147000.0
79,University of Michigan,Midwestern,52700.0,93000.0,50900.0,69400.0,128000.0,182000.0
80,Purdue University,Midwestern,51400.0,90500.0,49900.0,67400.0,121000.0,168000.0
81,Marquette University,Midwestern,48500.0,88400.0,49500.0,67400.0,121000.0,184000.0
82,DePauw University,Midwestern,41400.0,88200.0,49500.0,57400.0,133000.0,185000.0
83,University of Wisconsin (UW) - Madison,Midwestern,48900.0,87800.0,47400.0,62400.0,118000.0,170000.0
84,Bradley University,Midwestern,47000.0,87300.0,45900.0,64900.0,113000.0,151000.0
85,St. Olaf College,Midwestern,45300.0,86200.0,41300.0,61000.0,120000.0,185000.0
86,Michigan State University (MSU),Midwestern,46300.0,85300.0,44200.0,61500.0,119000.0,170000.0
87,DePaul University,Midwestern,46400.0,84800.0,50300.0,63900.0,115000.0,160000.0
88,Iowa State University,Midwestern,45400.0,84600.0,44400.0,60000.0,109000.0,147000.0
89,University of Minnesota,Midwestern,46200.0,84200.0,49000.0,63200.0,112000.0,148000.0
90,"Indiana University (IU), Bloomington",Midwestern,46300.0,84000.0,43600.0,60400.0,119000.0,178000.0
91,University of Iowa (UI),Midwestern,44700.0,83900.0,43300.0,61100.0,116000.0,163000.0
92,Ohio State University (OSU),Midwestern,44900.0,83700.0,45500.0,60700.0,116000.0,162000.0
93,Denison University,Midwestern,42000.0,83500.0,NaN,62100.0,122000.0,NaN
94,University of Illinois at Chicago,Midwestern,47500.0,81700.0,44700.0,58800.0,110000.0,146000.0
95,Oberlin College,Midwestern,43400.0,81600.0,NaN,46400.0,128000.0,NaN
96,University of Kansas,Midwestern,42400.0,81600.0,44800.0,57200.0,115000.0,156000.0
97,University of Missouri - Columbia,Midwestern,41700.0,81000.0,43500.0,57100.0,111000.0,156000.0
98,University of Nebraska,Midwestern,45700.0,80900.0,42200.0,56600.0,113000.0,156000.0
99,Northern Illinois University (NIU),Midwestern,43600.0,80800.0,43900.0,60200.0,111000.0,161000.0
100,Gustavus Adolphus College,Midwestern,44500.0,80600.0,NaN,49300.0,101000.0,NaN
101,University of North Dakota,Midwestern,44000.0,80600.0,43400.0,56400.0,111000.0,157000.0
102,Kansas State University (KSU),Midwestern,43300.0,79000.0,37200.0,54100.0,106000.0,138000.0
103,University of Wisconsin (UW) - Platteville,Midwestern,45800.0,78500.0,48400.0,61200.0,100000.0,139000.0
104,Wittenberg University,Midwestern,39200.0,78200.0,NaN,54100.0,131000.0,NaN
105,North Dakota State University (NDSU),Midwestern,45100.0,77800.0,39000.0,55800.0,100000.0,123000.0
106,Grinnell College,Midwestern,42600.0,76600.0,NaN,65100.0,116000.0,NaN
107,Wayne State University,Midwestern,42800.0,76100.0,40100.0,56200.0,101000.0,139000.0
108,University of Toledo,Midwestern,43100.0,75900.0,40100.0,54100.0,100000.0,133000.0
109,University of Wisconsin (UW) - Whitewater,Midwestern,40800.0,75500.0,38200.0,53500.0,99300.0,150000.0
110,Minnesota State University - Mankato,Midwestern,43300.0,74700.0,39500.0,53800.0,95700.0,140000.0
111,University of Wisconsin (UW) - Milwaukee,Midwestern,42300.0,74600.0,40600.0,54000.0,93700.0,123000.0
112,Western Michigan University (WMU),Midwestern,42300.0,73800.0,40100.0,52500.0,103000.0,135000.0
113,South Dakota State University (SDSU),Midwestern,41100.0,73500.0,34100.0,49900.0,99400.0,129000.0
114,Ohio University,Midwestern,42200.0,73400.0,36600.0,52800.0,106000.0,150000.0
115,Illinois State University,Midwestern,42000.0,73400.0,39100.0,55200.0,105000.0,142000.0
116,Cleveland State University,Midwestern,43500.0,73100.0,39500.0,51600.0,97000.0,137000.0
117,University of Nebraska at Omaha,Midwestern,41500.0,72600.0,39500.0,54400.0,97400.0,126000.0
118,Southern Illinois University Carbondale,Midwestern,43000.0,72500.0,38300.0,51300.0,99300.0,139000.0
119,Eastern Michigan University,Midwestern,40300.0,72100.0,37900.0,52800.0,95400.0,135000.0
120,Bowling Green State University,Midwestern,39800.0,72100.0,38200.0,51800.0,101000.0,146000.0
121,St. Cloud State University,Midwestern,41800.0,71400.0,38700.0,49400.0,101000.0,126000.0
122,University of Wisconsin (UW) - Parkside,Midwestern,40700.0,71400.0,40900.0,53100.0,84900.0,119000.0
123,University of Akron,Midwestern,41100.0,70300.0,40600.0,53300.0,95200.0,127000.0
124,Missouri State University (MSU),Midwestern,36100.0,69500.0,33300.0,46900.0,102000.0,134000.0
125,University of Wisconsin (UW) - La Crosse,Midwestern,42200.0,69300.0,37500.0,47200.0,93100.0,133000.0
126,University of Wisconsin (UW) - Stout,Midwestern,43600.0,68300.0,40900.0,50600.0,91600.0,136000.0
127,Robert Morris College (RMC),Midwestern,38500.0,68200.0,37300.0,47100.0,95000.0,128000.0
128,University of Missouri - St. Louis (UMSL),Midwestern,41400.0,67100.0,36800.0,49600.0,97600.0,144000.0
129,University of Wisconsin (UW) - Oshkosh,Midwestern,39300.0,66400.0,37700.0,49700.0,90100.0,138000.0
130,University of Missouri - Kansas City (UMKC),Midwestern,38900.0,65800.0,36300.0,48100.0,95800.0,124000.0
131,University of Wisconsin (UW) - Eau Claire,Midwestern,41400.0,64800.0,35000.0,47300.0,93100.0,125000.0
132,Ball State University (BSU),Midwestern,39100.0,64500.0,35500.0,48200.0,89300.0,128000.0
133,Park University,Midwestern,44300.0,64300.0,37200.0,45600.0,86400.0,113000.0
134,University of Wisconsin (UW) - Stevens Point,Midwestern,39800.0,64000.0,38400.0,45100.0,95400.0,128000.0
135,Kent State University,Midwestern,38700.0,62600.0,36100.0,45800.0,87000.0,124000.0
136,University of Wisconsin (UW) - Green Bay,Midwestern,35800.0,60600.0,35500.0,46800.0,81800.0,102000.0
137,Indiana Wesleyan University (IWU),Midwestern,39800.0,58500.0,39600.0,47800.0,78600.0,93400.0
138,Pittsburg State University,Midwestern,40400.0,58200.0,25600.0,46000.0,84600.0,117000.0
139,Davenport University,Midwestern,39700.0,46600.0,31600.0,38100.0,65600.0,85700.0
140,Black Hills State University,Midwestern,35300.0,43900.0,NaN,32200.0,60900.0,NaN
141,Rice University,Southern,64000.0,110000.0,55900.0,82100.0,141000.0,216000.0
142,Georgetown University,Southern,55000.0,110000.0,60300.0,85800.0,174000.0,248000.0
143,Duke University,Southern,58900.0,106000.0,56000.0,77400.0,149000.0,218000.0
144,Georgia Institute of Technology,Southern,58300.0,106000.0,67200.0,85200.0,137000.0,183000.0
145,Washington and Lee University,Southern,53600.0,104000.0,NaN,82800.0,146000.0,NaN
146,Vanderbilt University,Southern,51200.0,104000.0,49900.0,68100.0,147000.0,222000.0
147,Davidson College,Southern,46100.0,104000.0,NaN,70500.0,146000.0,NaN
148,University of Virginia (UVA),Southern,52700.0,103000.0,52200.0,71800.0,146000.0,215000.0
149,George Washington University (GWU),Southern,47000.0,97900.0,48400.0,69600.0,132000.0,194000.0
150,Texas A&M University,Southern,49700.0,96100.0,51100.0,71300.0,131000.0,171000.0
151,Tulane University,Southern,49100.0,95800.0,46500.0,64400.0,134000.0,185000.0
152,Virginia Polytechnic Institute and State Unive...,Southern,53500.0,95400.0,50600.0,71400.0,124000.0,163000.0
153,"University of Maryland, College Park",Southern,52000.0,95000.0,50400.0,68300.0,126000.0,166000.0
154,University of Richmond,Southern,48600.0,94600.0,44500.0,59400.0,151000.0,211000.0
155,University of Texas (UT) - Austin,Southern,49700.0,93900.0,50100.0,67400.0,129000.0,188000.0
156,Emory University,Southern,52000.0,91600.0,52500.0,63300.0,128000.0,192000.0
157,"American University, Washington D.C.",Southern,45300.0,90800.0,45200.0,62400.0,134000.0,169000.0
158,University of Tulsa,Southern,42400.0,88700.0,42300.0,60300.0,120000.0,197000.0
159,Baylor University,Southern,48300.0,88600.0,46300.0,60700.0,130000.0,200000.0
160,University of Florida (UF),Southern,47100.0,87900.0,45400.0,62900.0,120000.0,172000.0
161,Louisiana State University (LSU),Southern,46900.0,87800.0,43700.0,61300.0,120000.0,165000.0
162,George Mason University,Southern,47800.0,86900.0,51300.0,67200.0,114000.0,150000.0
163,Clemson University,Southern,48400.0,86000.0,50500.0,61800.0,111000.0,150000.0
164,University of Georgia (UGA),Southern,44100.0,86000.0,43100.0,57800.0,118000.0,164000.0
165,Auburn University,Southern,45400.0,84700.0,45400.0,62700.0,109000.0,145000.0
166,University of Delaware,Southern,45900.0,84500.0,44500.0,64000.0,119000.0,165000.0
167,Randolph-Macon College,Southern,42600.0,83600.0,NaN,54100.0,123000.0,NaN
168,North Carolina State University (NCSU),Southern,47200.0,83300.0,49200.0,64800.0,112000.0,153000.0
169,University of Oklahoma,Southern,44700.0,82900.0,41200.0,60300.0,114000.0,167000.0
170,University of Arkansas,Southern,44100.0,82800.0,43200.0,60700.0,113000.0,160000.0
171,University of Alabama at Huntsville (UAH),Southern,43100.0,82700.0,46100.0,67800.0,106000.0,132000.0
172,Howard University,Southern,46900.0,81800.0,43300.0,60000.0,109000.0,138000.0
173,University of North Carolina at Chapel Hill (U...,Southern,42900.0,81500.0,43400.0,57500.0,117000.0,155000.0
174,"University of Alabama, Tuscaloosa",Southern,41300.0,81400.0,40100.0,56500.0,117000.0,161000.0
175,University of Texas at Arlington (UTA),Southern,45400.0,80800.0,46400.0,61200.0,106000.0,138000.0
176,Oklahoma State University,Southern,42800.0,80700.0,40100.0,56500.0,114000.0,151000.0
177,Tennessee Technological University,Southern,46200.0,80000.0,42100.0,62600.0,99500.0,121000.0
178,University of Houston (UH),Southern,46000.0,79900.0,42000.0,56200.0,106000.0,141000.0
179,University of Mississippi,Southern,41400.0,79700.0,40400.0,53500.0,108000.0,186000.0
180,Lamar University,Southern,46500.0,79400.0,38700.0,51600.0,114000.0,158000.0
181,Mississippi State University (MSU),Southern,44500.0,79300.0,43300.0,58800.0,108000.0,151000.0
182,University of Kentucky (UK),Southern,42800.0,78300.0,43000.0,57300.0,107000.0,149000.0
183,Texas Christian University (TCU),Southern,45100.0,78100.0,42600.0,56600.0,122000.0,183000.0
184,West Virginia University (WVU),Southern,43100.0,78100.0,39700.0,55700.0,106000.0,141000.0
185,University of Maryland Baltimore County (UMBC),Southern,47000.0,77800.0,46900.0,59100.0,105000.0,130000.0
186,University of Louisiana (UL) at Lafayette,Southern,41100.0,76300.0,42000.0,54500.0,107000.0,163000.0
187,Florida International University (FIU),Southern,43200.0,75500.0,40500.0,55800.0,98200.0,136000.0
188,University of Tennessee,Southern,43800.0,74600.0,41900.0,53200.0,106000.0,153000.0
189,University of Arkansas - Monticello (UAM),Southern,39200.0,74500.0,NaN,46100.0,110000.0,NaN
190,University of North Carolina at Charlotte (UNCC),Southern,43100.0,74000.0,38200.0,53200.0,99500.0,133000.0
191,Georgia State University,Southern,41800.0,74000.0,43000.0,55300.0,99900.0,145000.0
192,LeTourneau University,Southern,49500.0,73800.0,41200.0,52700.0,95200.0,126000.0
193,Florida State University (FSU),Southern,42100.0,73000.0,39600.0,52800.0,107000.0,156000.0
194,University of Texas at El Paso (UTEP),Southern,43400.0,72100.0,37700.0,50400.0,99500.0,133000.0
195,University of Central Florida (UCF),Southern,42600.0,71700.0,39500.0,51500.0,98400.0,125000.0
196,University of South Carolina,Southern,40000.0,71700.0,36300.0,49900.0,98400.0,131000.0
197,Florida Atlantic University (FAU),Southern,42600.0,71100.0,40700.0,53000.0,99500.0,137000.0
198,University of South Florida (USF),Southern,41100.0,71100.0,39600.0,51500.0,98100.0,131000.0
199,University of Texas at San Antonio (UTSA),Southern,42500.0,70700.0,39100.0,49800.0,92700.0,121000.0
200,University of Alabama at Birmingham (UAB),Southern,39200.0,70100.0,43000.0,53400.0,91400.0,125000.0
201,University of Memphis (U of M),Southern,41400.0,69700.0,36100.0,49100.0,93500.0,127000.0
202,Appalachian State University,Southern,40400.0,69100.0,37200.0,50400.0,90800.0,115000.0
203,Virginia Commonwealth University (VCU),Southern,42000.0,68400.0,37400.0,51900.0,100000.0,123000.0
204,East Carolina University (ECU),Southern,40200.0,67500.0,38400.0,52000.0,98700.0,151000.0
205,Western Carolina University,Southern,36900.0,66600.0,39000.0,49500.0,94400.0,133000.0
206,Jacksonville University,Southern,46700.0,66200.0,36700.0,47200.0,88500.0,121000.0
207,University of North Carolina at Wilmington (UNCW),Southern,37500.0,64400.0,32100.0,46600.0,97100.0,129000.0
208,Oklahoma City University,Southern,40000.0,64300.0,NaN,45400.0,80600.0,NaN
209,Arkansas State University (ASU),Southern,38700.0,63300.0,33600.0,45300.0,83900.0,118000.0
210,Tarleton State University (TSU),Southern,40800.0,62400.0,32100.0,47400.0,80400.0,126000.0
211,Morehead State University,Southern,34800.0,60600.0,34300.0,46500.0,72000.0,91300.0
212,Mississippi College,Southern,35400.0,60400.0,NaN,43900.0,80400.0,NaN
213,Dallas Baptist University,Southern,39400.0,60200.0,38500.0,50300.0,81800.0,98100.0

In [ ]:
# # format salary columns
# for col in df_mod.columns[2:]:
#     df_mod[col] = df_mod[col].astype(str) # cast as string
    
#     # remove non-numeric characters
#     df_mod[col] = df_mod[col].str.replace(',', '')
#     df_mod[col] = df_mod[col].str.replace('$', '')

#     df_mod[col] = df_mod[col].astype(float).round(decimals=0) # cast back to float

In [6]:
df_mod.dtypes

School Name                           object
Region                                object
Starting Median Salary               float64
Mid-Career Median Salary             float64
Mid-Career 10th Percentile Salary    float64
Mid-Career 25th Percentile Salary    float64
Mid-Career 75th Percentile Salary    float64
Mid-Career 90th Percentile Salary    float64
dtype: object

In [7]:
df_mod.groupby('Region').mean().round()

,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
Region,,,,,,
California,51032.0,93132.0,47777.0,67154.0,127350.0,167909.0
Midwestern,44225.0,78180.0,43077.0,57027.0,107594.0,147689.0
Northeastern,48496.0,91352.0,49101.0,65479.0,129576.0,181927.0
Southern,44522.0,79505.0,43075.0,57506.0,109662.0,152769.0
Western,44414.0,78200.0,42985.0,56581.0,106026.0,143824.0

In [8]:
df_mod.groupby('Region')['Starting Median Salary'].describe().round()

,count,mean,std,min,25%,50%,75%,max
Region,,,,,,,,
California,28.0,51032.0,8982.0,38000.0,45650.0,48450.0,52825.0,75500.0
Midwestern,71.0,44225.0,5068.0,35300.0,41100.0,43100.0,46250.0,57100.0
Northeastern,100.0,48496.0,7159.0,36900.0,43150.0,47000.0,52825.0,72200.0
Southern,79.0,44522.0,5626.0,34500.0,41100.0,43400.0,47050.0,64000.0
Western,42.0,44414.0,3935.0,37300.0,42050.0,44850.0,46575.0,58100.0

In [ ]:
# # cast as string
# df_mod['Starting Median Salary'] = df_mod['Starting Median Salary'].astype(str)

# # format strings
# df_mod['Starting Median Salary'] = df_mod['Starting Median Salary'].str.replace(',', '')
# df_mod['Starting Median Salary'] = df_mod['Starting Median Salary'].str.replace('$', '')

# # cast back to float
# df_mod['Starting Median Salary'] = df_mod['Starting Median Salary'].astype(float).round(decimals=0)

# df_mod['Starting Median Salary'].describe().round()

### Changelog
---
    - originally planned to download data as csv, but figured it would be good practice to make an api call and download it that way. Haven't worked with APIs before. Keggle apparently has its own library?
    - this still downloads locally and I doubt others would successfully be able to run this.
    - having issues using kaggle api to download dataset
2/19/20
    - first time keeping track of daily changes to notebook
    - abondoned implimenting api for now, prioritized traversing through data and visualizing
    - second question filepath is incorrect, which is why lists are not building correctly
2/20/20
    - successfully printed the average median salary for each school type in a nice format
    - code is clunky and not clean. working to figure out how I can clean it up. also working on visualizing means
2/21/20
    - cleaned up code by removing redundant list and learning how to initialize multiple lists in one line
    - created dictionary with school type as keys and average median salaries as the paired values
    - used zip function with * positional argument to easily graph dictionary on bar chart
2/24/20
    - formatted second bar chart
    - cleaned up code, added comments
    - created a git repository and uploaded this notebook to github
2/26/20
    - moved directories, updated filepaths
    - imported and read csv
2/27/20
    - Ran into the same string problem as earlier. Formatted specific column (starting median salary) into float
2/28/20
    - successfully used pandas to describe the starting median salary column and grouped that by region. 
    - HOWEVER, it only works because that is the only data column that is formatted into a float (i think). If all the salaries were formatted into floats, then I would be stuck with the problem of not filtering out all other columns while still grouping by region.
2/29/20
    - formatted all the columns with salary data.
    - I was correct yesterday in thinking that describe method was only displaying the correct results because it was the only column with a float type. Now figuring out how to get statistics for a single column grouped by another column. Also need to create a separate method to format strings. Would make code cleaner.
3/1/20
    - Figured out solution for using describe on a single while using groupby(). Just needed to index column.
    - Cleaned code. Added comments
    - started to create a function to format objects into floats, but got stuck
3/2/20
    - created separate function to format salary columns into float type
    - updated github